/*
    Copyright (C) 2011 Collabora Ltd. <info@collabora.co.uk>
      @author George Kiagiadakis <george.kiagiadakis@collabora.co.uk>

    This library is free software; you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published
    by the Free Software Foundation; either version 2.1 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include "qf.h"
#include "session.h"
#include <QGlib/Value>

#include <farstream/fs-session.h>

namespace QFs {

namespace Private {
    void registerWrapperConstructors(); //generated by codegen
    void registerValueVTables() {
        struct ValueVTable_FsSession
        {
            static void get(const QGlib::Value &value, void *data)
            {
                data = g_value_get_pointer(value);
                if(!FS_IS_SESSION(data)) {
                    data = 0;
                }
            }
            static void set(QGlib::Value &value, const void *data)
            {
                if(FS_IS_SESSION(data)) {
                    g_value_set_pointer(value, const_cast<void *>(data));
                }
            }
        };
        QGlib::Value::registerValueVTable(
            QGlib::GetType<SessionPtr>(),
            QGlib::ValueVTable(ValueVTable_FsSession::set, ValueVTable_FsSession::get));

    }
};

void init()
{
    Private::registerWrapperConstructors();
    Private::registerValueVTables();
}



} //namespace QFs

#include "qf.moc"
